export { default as Featured } from './featured'
export { default as Header } from './header'
export { default as Layout } from './layout'
export { default as Skills } from './skills'
export { default as About } from './about'
// export { default as Switch } from './switch'
export { default as ProjectPreview } from './project-preview'
export { default as Project } from './project'
export { default as Contact } from './contact'
export { default as SEO } from './seo'
